# render.yaml
services:
  - type: web # Specifies a web service
    name: flattr-backend # Name for your service on Render
    env: node # Use the Node.js environment
    plan: free # Or choose a paid plan like 'starter'
    rootDir: apps/backend # Specify the directory for this service within the monorepo
    buildCommand: "pnpm install --frozen-lockfile --prod && pnpm run build" # Command to build the backend
    startCommand: "pnpm run start:prod" # Command to start the backend
    envVars:
      - key: NODE_VERSION # Optional: Specify Node version if needed, e.g., 18.17.1
        value: 20 # Or your desired Node.js version compatible with NestJS
      - key: DATABASE_URL # Example: If using Render Postgres
        fromDatabase:
          name: your-database-name # Replace with your Render DB name
          property: connectionString
      # --- Add your specific environment variables below ---
      - key: JWT_SECRET
        sync: false # Keep secrets out of the yaml if preferred, set in dashboard
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      # Add other necessary env vars like TRUECALLER keys if needed
      # - key: TRUECALLER_CLIENT_ID
      #   sync: false
      # - key: TRUECALLER_CLIENT_SECRET
      #   sync: false
      - key: FRONTEND_URL # Example: Will be the URL of your deployed frontend
        value: https://your-frontend-url.onrender.com # Replace with your actual frontend URL later
      # PORT is automatically set by Render 